---
title: "threat_index"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# load packages
library(tidyverse)
library(sf)
library(here)
library(raster)
```

This RMarkdown is an exploration of the data used to create the threat index. 

Data sources used:
- **Wildfire Hazard Index:** https://tukmangeospatial.egnyte.com/dl/BKVGCGmqCq
- **SLR and storm surge:** https://ourcoastourfuture.org/hazard-map/
- **Landslide susceptibility:** https://gis.conservation.ca.gov/portal/home/item.html?id=87289025c11d4ba7ae65f0f472bf7c2d

```{r, echo=FALSE}
##### read in the data #####
fire_hazard <- raster::raster(here("data/clean/fire_hazard_index.tif"))
landslide_risk <- raster::raster(here("data/clean/soco_landslide_risk/ls_risk_rcl.tif"))

```

```{r, echo = FALSE}
#### Get base shapefiles ####
ca_state <- sf::read_sf(here("data/clean/ca_state_boundary/ca_state_boundary.shp"))
sonoma_county <- sf::read_sf(here("data/clean/sonoma_county_boundary/sonoma_county_boundary.shp"))

ggplot() +
  geom_sf(data = ca_state) +
  geom_sf(data = sonoma_county, fill = "red", alpha = 0.5) +
  coord_sf(xlim = c(-124,-122), ylim = c(38,39))
```

```{r}
# raster resampler in case this changes
raster_resample <- landslide_risk
resample_crs <- crs(landslide_risk)
```


### Wildfire Hazard Index
- Range: 1-5 (Low to Extreme)

```{r}
# visualize
plot(fire_hazard)

# resample 
fire_crs <- projectRaster(fire_hazard, crs = resample_crs)
fire_rsmpl <- raster::resample(x = fire_crs, y = landslide_risk, method = "ngb")
```


### Combined indices

```{r}
threat_index <- fire_rsmpl + landslide_risk

threat_index_df <- as.data.frame(threat_index, xy = TRUE)

soco_crs <- st_transform(sonoma_county, resample_crs)

pal <- colorRampPalette(c("white", "yellow", "red"))

plot(threat_index, col = pal(10))
plot(soco_crs, add = TRUE, col = NA)
```

