---
title: "Sonoma County BCM data"
output: html_document
date: '2022-03-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
library(tidyverse)
library(sf)
library(here)
library(ggthemes)
library(raster)
library(RColorBrewer)
library(measurements)
```

```{r, include=FALSE}
### read in shapefiles ###

## Administrative boundaries
soco_bound <- read_sf(here("data/clean/sonoma_county_boundary/sonoma_county_boundary.shp"))
ca_state <- sf::read_sf(here("data/clean/ca_state_boundary/ca_state_boundary.shp"))

# BCM projected data
bcm_proj_data <- read_sf(here("data/clean/soco_bcm/soco_bcm_full_ws.shp"))
bcm_hist <- read_csv(here("data/clean/soco_bcm/bcm_hist_base.csv"))

# ecoregions
ecoregion <- read_sf(here("data/clean/soco_ecoregion_l4/soco_ecoregion_l4_simp.shp"))
```

```{r, include=FALSE}
# source functions
source(here("R/utils/bcm_plot.R"))
```

```{r, include=FALSE}
# tidy historical data
bcm_hist_tidy <- bcm_hist %>% 
  dplyr::select(-"...1", -gcm, -wyear_group) %>% 
  # convert to imperial
    mutate( stor = conv_unit(stor,"mm", "inch"),
          rch = conv_unit(rch,"mm", "inch"),
          run = conv_unit(run,"mm", "inch"),
          aet = conv_unit(aet,"mm", "inch"),
          cwd = conv_unit(cwd,"mm", "inch"),
          tmax = conv_unit(tmax,"C", "F"),
          tmin = conv_unit(tmin,"C", "F"),
          ppt = conv_unit(ppt,"mm", "inch"),
          pet = conv_unit(pet,"mm", "inch")) %>% 
  pivot_longer(c("stor", "rch", "run", "aet", "cwd", "tmax", "tmin", "ppt", "pet"), names_to = "climate_variables", values_to = "hist_values") %>% 
  mutate(watershed_num = as.character(watershed_num))
```

```{r, include=FALSE}
# clean up the bcm data
bcm_proj_metric <- bcm_proj_data %>% 
  dplyr::select(-Area_acre) %>% 
  dplyr::rename(watershed_num = watershed_) %>% 
  dplyr::mutate(watershed_num = as.character(watershed_num)) %>% 
  dplyr::rename(wyear_group = wyear_grou) %>% 
  dplyr::mutate(hst_39 = ifelse(gcm == "HST" & wyear_group == "2010-2039", 1, 0)) %>% 
  dplyr::filter(hst_39 != 1) %>% 
  dplyr::select(-hst_39)

# convert to imperial units
bcm_proj <- bcm_proj_metric %>% 
  mutate( stor = conv_unit(stor,"mm", "inch"),
          rch = conv_unit(rch,"mm", "inch"),
          run = conv_unit(run,"mm", "inch"),
          aet = conv_unit(aet,"mm", "inch"),
          cwd = conv_unit(cwd,"mm", "inch"),
          tmax = conv_unit(tmax,"C", "F"),
          tmin = conv_unit(tmin,"C", "F"),
          ppt = conv_unit(ppt,"mm", "inch"),
          pet = conv_unit(pet,"mm", "inch"))
```


```{r, include=FALSE}
# put historical change and future projected conditions into a tidy format
bcm_tidy <- bcm_proj %>% 
  # convert to tidy format
  pivot_longer(c("stor", "rch", "run", "aet", "cwd", "tmax", "tmin", "ppt", "pet"),
               names_to = "climate_variables", values_to = "values") %>% 
  left_join(bcm_hist_tidy, by=c("watershed_num", "climate_variables")) %>% 
  mutate(change_from_hist = values - hist_values) %>% 
  st_as_sf()
```

```{r, include=FALSE}
# filter to just the hot and dry scenario
bcm_cnrm <- bcm_proj %>% 
  filter(gcm %in% c("CNRM_rcp85", "HST"))

# filter to just the hot and dry scenario
bcm_miroc <- bcm_proj %>% 
  filter(gcm %in% c("MIROC_rcp85", "HST"))
```

```{r}
# function to calculate what are the changes compared to the historical baseline for both climate projections?
calc_chng_frm_hist = function(climate_variable, wy_group) {
  
  bcm_eoc <- bcm_tidy %>% 
    filter(climate_variables == climate_variable) %>% 
    filter(wyear_group == wy_group) %>% 
    group_by(gcm) %>% 
    mutate(min_ind = min(change_from_hist)) %>% 
    mutate(max_ind = max(change_from_hist)) %>% 
    mutate(av_ind = mean(change_from_hist)) %>% 
    mutate(range = paste0(round(av_ind, 1), " (", round(min_ind, 1), "-", round(max_ind, 1), ")"))
  
  return(bcm_eoc)
  
}
```

```{r}
#' plot_bcm_change
#'
#' @param bcm_data filtered bcm data
#' @param color_palette color palette for the map
#' @param legend_limits limits for the legend
#' @param unit_type unit of measurement 
#'
#' @return plot
#'
#' @examples plot_bcm_change(max_temp_2040_miroc, "YlOrBr", c(5,7))

plot_bcm_change = function(bcm_data, color_palette, legend_limits, unit_type){
  
  bcm_plot <- ggplot() +
    geom_sf(data = ca_state, color = "grey", fill = "#e2e2e2") +
    geom_sf(data = bcm_data, aes(fill = change_from_hist), color = NA) +
    scale_fill_distiller(palette = color_palette, direction = 1, limits = legend_limits) +
    geom_sf(data = ecoregion, fill = NA, color = "black", size = 1) +
    labs(fill = unit_type) +
    coord_sf(xlim = c(-123.5,-122.2), ylim = c(38.1,38.85)) +
    theme_map() +
    theme(panel.background = element_rect(fill = "#add8e6", color = NA))
  
  return(bcm_plot)
  
}
```


#### **Max temperature**

```{r, echo = FALSE}
bcm_plot(bcm_miroc, bcm_miroc$tmax, "Temperature (°F)", "MIROC RCP 8.5 (hot, low rainfall)", "YlOrBr", col_limits = c(60, 85))
bcm_plot(bcm_cnrm, bcm_cnrm$tmax, "Temperature (°F)", "CNRM RCP 8.5 (warm, high rainfall)", "YlOrBr", col_limits = c(60, 85))
```

Hot and low rainfall -- 2040-2069 change from historical baseline

```{r, echo = FALSE}
# check how much average chnnge
max_temp_2040_miroc <- calc_chng_frm_hist("tmax", "2040-2069") %>% 
    filter(gcm == "MIROC_rcp85")

max_temp_2040_plt <- plot_bcm_change(max_temp_2040_miroc, "YlOrBr", c(5,7), "Temperature (°F)")
max_temp_2040_plt


ggsave(filename = "bcm_tmax_miroc_2040-2069.png", plot = max_temp_2040_plt, path = here("output/maps/"), dpi = 350)

```


#### **Min temperature**

```{r, echo = FALSE}
bcm_plot(bcm_miroc, bcm_miroc$tmin, "Temperature (°F)", "MIROC RCP 8.5 (hot, low rainfall)", "Blues", pal_dir = -1, col_limits = c(40, 60))
bcm_plot(bcm_cnrm, bcm_cnrm$tmin, "Temperature (°F)", "CNRM RCP 8.5 (warm, high rainfall)", "Blues", pal_dir = -1, col_limits = c(40, 60))
```
```{r}
# check how much average chnnge
min_temp_2040_miroc <- calc_chng_frm_hist("tmin", "2040-2069") %>% 
    filter(gcm == "MIROC_rcp85")

min_temp_2040_plt <- plot_bcm_change(min_temp_2040_miroc, "Blues", c(5,6.5), "Temperature (°F)")
min_temp_2040_plt


ggsave(filename = "bcm_tmin_miroc_2040-2069.png", plot = min_temp_2040_plt, path = here("output/maps/"), dpi = 350)
```


#### **Precipitation**

```{r, echo = FALSE}
bcm_plot(bcm_miroc, bcm_miroc$ppt, "Precipitation (in)", "MIROC RCP 8.5 (hot, low rainfall)", "YlGnBu", col_limits = c(16, 94))
bcm_plot(bcm_cnrm, bcm_cnrm$ppt, "Precipitation (in)", "CNRM RCP 8.5 (warm, high rainfall)", "YlGnBu", col_limits = c(16, 94))
```
```{r, echo = FALSE}
bcm_proj %>% 
  filter(gcm != "HST") %>% 
  ggplot(aes(x = ppt)) +
  geom_histogram(aes(fill = gcm)) +
  scale_y_continuous(expand = c(0,0))

```

```{r, echo = FALSE}
# What are the changes compared to the historical baseline at the end of the century for both climate projections?
bcm_precip_2040_miroc <- calc_chng_frm_hist("ppt", "2040-2069")%>% 
    filter(gcm == "MIROC_rcp85")

bcm_precip_2040_miroc_plt <- plot_bcm_change(bcm_precip_2040_miroc, "YlGnBu", c(-14.5,-3), "Precipitation (in)")
bcm_precip_2040_miroc_plt


ggsave(filename = "bcm_precip_miroc_2040-2069.png", plot = bcm_precip_2040_miroc_plt, path = here("output/maps/"), dpi = 350)


```


#### **Climatic Water Deficit**

```{r, echo = FALSE}
bcm_plot(bcm_miroc, bcm_miroc$cwd, "Climatic Water Deficit (in)", "MIROC RCP 8.5 (hot, low rainfall)", "YlOrRd", col_limits = c(20, 40))
bcm_plot(bcm_cnrm, bcm_cnrm$cwd, "Climatic Water Deficit (in)", "CNRM RCP 8.5 (warm, high rainfall)", "YlOrRd", col_limits = c(20, 40))
```


```{r, echo = FALSE}
# What are the changes compared to the historical baseline at the end of the century for both climate projections?
bcm_cwd_2040_miroc <- calc_chng_frm_hist("cwd", "2040-2069")%>% 
    filter(gcm == "MIROC_rcp85")

bcm_cwd_2040_miroc_plt <- plot_bcm_change(bcm_cwd_2040_miroc, "YlOrRd", c(3,5.3), "Climatic Water Deficit (in)")
bcm_cwd_2040_miroc_plt


ggsave(filename = "bcm_cwd_miroc_2040-2069.png", plot = bcm_cwd_2040_miroc_plt, path = here("output/maps/"), dpi = 350)

```
```

