---
title: "Threat Index Data processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# load packages
library(tidyverse)
library(sf)
library(here)
library(raster)
library(fasterize)
```

```{r}
# source functions
source(here("R/utils/change_to_raster.R"))
```


This Rmarkdown is for any data cleaning or joining necessary for the threat index variables.

```{r, echo=FALSE}
##### read in the data #####

# sonoma county
sonoma_county <- sf::read_sf(here("data/clean/sonoma_county_boundary/sonoma_county_boundary.shp"))

# Sonoma Wildfire Hazard Index
raw_fire_hazard <- raster::raster(here("data/raw/sc_wildfire_hazard_02.23.21/HAZARD_V5_96FT_CLASSIFIED.tif"))

# SLR 75 cm
slr_75cm <- read_sf(here("data/raw/sonoma_flooding_slr075/flooding/v2.2/sonoma_fldhazd_slr075_w000.shp"))
bdb_slr_75cm <- read_sf(here("data/raw/sonoma_flooding_slr075/flooding/v2.0/sonoma_fldhazd_slr075_w000.shp"))
sfb_slr_75cm <- read_sf(here("data/raw/sonoma_flooding_slr075/flooding/v2.1/sfb_fldhazd_slr075_w000.shp"))

# SLR 75 cm + 100 year storm
slr_75cm_100yr <- read_sf(here("data/raw/sonoma_flooding_slr075/flooding/v2.2/sonoma_fldhazd_slr075_w100.shp"))
bdb_slr_75cm_100yr <- read_sf(here("data/raw/sonoma_flooding_slr075/flooding/v2.0/sonoma_fldhazd_slr075_w100.shp"))
sfb_slr_75cm_100yr <- read_sf(here("data/raw/sonoma_flooding_slr075/flooding/v2.1/sfb_fldhazd_slr075_w100.shp"))

# SLR 200 cm
slr_200cm <- read_sf(here("data/raw/sonoma_flooding_slr200/flooding/v2.2/sonoma_fldhazd_slr200_w000.shp"))
bdb_slr_200cm <- read_sf(here("data/raw/sonoma_flooding_slr200/flooding/v2.0/sonoma_fldhazd_slr200_w000.shp"))
sfb_slr_200cm <- read_sf(here("data/raw/sonoma_flooding_slr200/flooding/v2.1/sfb_fldhazd_slr200_w000.shp"))

# SLR 200 cm + 100 year storm
slr_200cm_100yr <- read_sf(here("data/raw/sonoma_flooding_slr200/flooding/v2.2/sonoma_fldhazd_slr200_w100.shp"))
bdb_slr_200cm_100yr <- read_sf(here("data/raw/sonoma_flooding_slr200/flooding/v2.0/sonoma_fldhazd_slr200_w100.shp"))
sfb_slr_200cm_100yr <- read_sf(here("data/raw/sonoma_flooding_slr200/flooding/v2.1/sfb_fldhazd_slr200_w100.shp"))

# Landslide susceptibility
ca_landslide <- raster::raster(here("data/raw/ca_landslide_susceptibility_20181001/ms58_ls_susceptibility_20181001.tif"))

# Santa Rosa UHII
santa_rosa_uhi <- read_sf(here("data/raw/santa_rosa_uhii/Santa_Rosa_UHII.shp"))
```

Create an empty raster to rasterize polygons with

```{r}
# Reclassification matrix for empty raster
rcl_matrix <- c(-Inf, Inf, 0)

# Reclassify the depth layer to make it an empty raster
empty_raster <- reclassify(raw_fire_hazard, rcl= rcl_matrix)

```

# Wildfire Hazard Index
```{r}
# get rid of black background values
rcl_fix <- c(5, Inf, 0)
fire_hazard_rcl <- reclassify(raw_fire_hazard, rcl_fix)

# write raster to clean data folder
writeRaster(fire_hazard_rcl, here("data/clean/fire_hazard_index.tif"))

```


# Sea Level Rise

### Combine SLR layers into one polygon

```{r}
# function to combine all the slr regions into one polygon
combine_slr = function(outer_sonoma, bdg_bay, sf_bay, sonoma_county){
  
  # change sonoma county crs to flood layer crs
  soco_crs <- st_transform(sonoma_county, st_crs(sf_bay))

  # crop sf bay to sonoma county
  sfb_crop <- st_crop(sf_bay, soco_crs)
  
  # use st_combine to simplify polygons
  outer_sonoma_comb <- st_combine(outer_sonoma)
  bdg_bay_comb <- st_combine(bdg_bay)
  
  # combine outer coast and bodega bay
  sonoma_bdb <- st_union(outer_sonoma_comb, bdg_bay_comb)
  
  # combine San Fracisco Bay
  all_slr <- st_union(sonoma_bdb, sfb_crop)
  
  return(all_slr)
  
}

# run the function and save the polygon
all_fld_200cm <- combine_slr(slr_200cm, bdb_slr_200cm, sfb_slr_200cm, sonoma_county)
write_sf(all_fld_200cm, here("data/clean/fldhazd_slr200_w000/all_fldhazd_slr200_w000.shp"))

all_fld_200cm_100yr <- combine_slr(slr_200cm_100yr, bdb_slr_200cm_100yr, sfb_slr_200cm_100yr, sonoma_county)
write_sf(all_fld_200cm_100yr, here("data/clean/fldhazd_slr200_w100/all_fldhazd_slr200_w100.shp"))

all_fld_75cm <- combine_slr(slr_75cm, bdb_slr_75cm, sfb_slr_75cm, sonoma_county)
write_sf(all_fld_75cm, here("data/clean/fldhazd_slr75_w000/all_fldhazd_slr75_w000.shp"))

all_fld_75cm_100yr <- combine_slr(slr_75cm_100yr, bdb_slr_75cm_100yr, sfb_slr_75cm_100yr, sonoma_county)
write_sf(all_fld_75cm_100yr, here("data/clean/fldhazd_slr75_w100/all_fldhazd_slr75_w100.shp"))

```


```{r}

# read in the cleaned dataframes
all_fld_200cm <- read_sf(here("data/clean/fldhazd_slr200_w000/all_fldhazd_slr200_w000.shp"))
all_fld_200cm_100yr <- read_sf(here("data/clean/fldhazd_slr200_w100/all_fldhazd_slr200_w100.shp"))

# just get the difference between slr scenarios
slr_200cm_100yr_only <- st_difference(all_fld_200cm_100yr, all_fld_200cm) 
```


```{r}
# check if worked
ggplot() +
 # geom_sf(data = sonoma_county, fill = "light grey") +
  geom_sf(data = slr_200cm_100yr_only, fill = "green", color = "green")
```

### Rasterize the polygons

```{r}
slr_200cm_raster <- change_to_raster(all_fld_200cm, empty_raster, rank = 2)
slr_200cm_100yr_raster <- change_to_raster(slr_200cm_100yr_only, empty_raster, rank = 1)

# combine into one raster
slr_raster <- slr_200cm_raster + slr_200cm_100yr_raster
plot(slr_raster)

```

# Landslides

```{r}
# just get sonoma county landslide risk
soco_ls_crs <- st_transform(sonoma_county, st_crs(ca_landslide)) # reproject the sonoma county shapefile to the landslide crs
ca_ls_crop <- raster::crop(ca_landslide, soco_ls_crs) # crop the raster to the extent of sonoma county boundary
soco_landslide <- raster::mask(x = ca_ls_crop, mask = soco_ls_crs) # mask the raster to sonoma county boundar
writeRaster(soco_landslide, here("data/clean/soco_landslide_risk/ls_risk.tif")) # save new raster

plot(soco_landslide)

```

```{r}
# reclassify the ranks to be 1-5 instead of 1-10
ls_rcl_matrix <- c(-1, 0, 0,
                   0, 2, 1,
                   2, 4, 2,
                   4, 6, 3,
                   6, 8, 4,
                   8, 10, 5) # reclassification matrix
soco_landslide_rcl <- reclassify(soco_landslide, rcl= ls_rcl_matrix) # reclassify raster
writeRaster(soco_landslide_rcl, here("data/clean/soco_landslide_risk/ls_risk_rcl.tif"), overwrite = TRUE) # save reclassified raster

plot(soco_landslide_rcl)
```

# Urban Heat Island Index

```{r}
# visualize the data 

ggplot() +
  geom_sf(data = sonoma_county) +
  geom_sf(data = santa_rosa_uhi, aes(fill = DegHourDay)) +
  scale_fill_continuous(type = "viridis")

hist(santa_rosa_uhi$DegHourDay)
  
```

